MB-0002 test

diff --git a/commit-msg b/commit-msg
--- a/commit-msg
+++ b/commit-msg
@@ -1,14 +1,14 @@
 #!/bin/sh
 
-exec < /dev/tty || echo "Please use cli"
+exec < /dev/tty || echo "Commit message invalid!"
 MESSAGE=`cat .git/COMMIT_EDITMSG`
 
 function patternCheck(){
 	COMMIT_MESSAGE=$1
 	if [[ ! "$COMMIT_MESSAGE" =~ ([a-zA-Z]{2})(-[0-9]{4}) ]];then
-		echo "Commit message:$COMMIT_MESSAGE \nShould match [A-Z]{2}-[0-9]{4}*"
+		echo "Commit message invalid!\nShould match [A-Z]{2}-[0-9]{4}*"
 		echo "Please enter a new MESSAGE"
-		read NEW_MESSAGE
+		read NEW_MESSAGE || exit 2
 		patternCheck "$NEW_MESSAGE"
 	else
 		COMMIT_MESSAGE=$COMMIT_MESSAGE
